spring:
  application:
    name: logistica

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/logistics_db}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}

  sql:
    init:
      mode: always

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  server:
    port: 8080

  jackson:
    time-zone: America/Bogota

server:
  port: 8080

app:
  jwt:
    secret: 1234567890123456789012345678901234567890123456789012345678901234
    expiration: 86400000
  rabbit:
    exchange: envios.exchange
    queue: envios.queue
    routing-key: envio.creado